package shuttle.hci.com;

public class Constants {
	public static final String[] PLACES = new String[]{
		"Donald P. Jacobs Center",
		"620 Lincoln Street",
		"Elder Residence Hall",
		"Delta Chi Fraternity",
		"Patten Gymnasium",
		"584 Lincoln Residence Hall",
		"Beta Theta Pi Fraternity",
		"Phi Delta Theta Fraternity",
		"2335 Sheridan Road",
		"Lambda Chi Alpha Fraternity",
		"Sigma Phi Epsilon Fraternity",
		"Goodrich House Residence Hall",
		"Pi Kappa Alpha Fraternity",
		"Chi Psi Fraternity",
		"Lindgren Hall",
		"Delta Upsilon Fraternity",
		"College of Cultural & Community Studies",
		"Foster House Residence Hall",
		"2251 Sheridan Road Residence Hall",
		"Zeta Beta Tau Fraternity",
		"Theta Chi Fraternity",
		"566 Lincoln Street",
		"Alpha Epsilon Pi Fraternity",
		"Kemper Residence Hall",
		"Slivka Residence Hall",
		"Ayers College of Commerce & Industry",
		"McCulloch Residence Hall",
		"Bobb Residence Hall",
		"Henry Crown Sports Pavilion / Norris Aquatic Center",
		"Combe Tennis Center",
		"Technological Institute",
		"Frances Searle Building",
		"Lakeside Fields",
		"Seeley G. Mudd Science and Engineering Library",
		"Cook Hall",
		"Hogan Building",
		"Pancoe-NSUHS Life Sciences Pavilion",
		"James L Allen Center",
		"Ryan Hall",
		"Silverman Hall",
		"Ford Motor Company Engineering Design Center",
		"Shakespeare Garden",
		"Catalysis Center",
		"Dearborn Observatory",
		"Garrett-Evangelical Theological Seminary",
		"Shanley Hall",
		"Lunt Hall",
		"Swift Hall",
		"Cresap Laboratory",
		"Central Utility Plant",
		"Andersen Hall",
		"Donald P. Jacobs Center",
		"Deering Meadow",
		"Deering Library",
		"University Library",
		"Norris University Center",
		"Pick-Staiger Concert Hall",
		"Annie May Swift Hall",
		"University Hall",
		"Weber Arch",
		"Harris Hall",
		"West Fairchild (International Studies Residential College)",
		"Crowe Hall",
		"Kresge Hall",
		"East Fairchild (Communications Residential College)",
		"The McCormick Tribune Center",
		"Fisk Hall",
		"Locy Hall",
		"John J. Louis Hall",
		"Theatre and Interpretation Center: Dance Center, Louis Theater, and Barber Theater",
		"Block Museum of Art, Mary and Leigh",
		"Marjorie Ward Marshall Dance Center",
		"Regenstein Hall of Music",
		"Boat House",
	"Sorority Quad"};


}
